[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile.railway"

[deploy]
startCommand = "dotnet trAInr.API.dll"
healthcheckPath = "/swagger"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10